Config passporst.js with jwt & register & login endpoints
sef-global/scholarx-backend pull request #13
Opened 2023-07-19 18:06 UTC by sathsarabandaraj

## Purpose

- The purpose of this PR is to fix #6 

## Goals

- Basic authentication to the API

## Approach

- Config passport.js Passport.js and JWT
- Add basic auth endpoints with controllers

### Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2023-07-20 14:50 UTC, anjula-sack requested changes
Good job! @sathsarabandaraj 
Can you the relevant tests to this?

2023-07-20 14:50 UTC, anjula-sack commented on src/configs/passport.ts
> +const JWT_SECRET = 'Nc$ykT*lUW3567^$@&iC1tpR$H$b29HJ'; // Same secret used for token creation
Use the env variable here

2023-07-20 14:50 UTC, anjula-sack commented on src/entity/user.entity.ts
> +// src/entity/user.entity.ts
```suggestion
```

2023-07-20 16:09 UTC, anjula-sack requested changes

2023-07-20 16:09 UTC, anjula-sack commented on src/app.ts
> +app.use('/api', userRouter);
Let's change them like below, 

```suggestion
app.use('/api/auth', authRouter);
```

2023-07-20 16:21 UTC, anjula-sack requested changes

2023-07-20 16:21 UTC, anjula-sack commented on src/controllers/user.controller.ts
> +  }
Let's move this to services, authServices.ts

2023-07-20 17:13 UTC, anjula-sack requested changes

2023-07-20 17:13 UTC, anjula-sack commented on src/controllers/user.controller.ts
> +    if (!email || !password || !contact_email || !first_name || !last_name || !image_url || !linkedin_url) {
Only these are required. @sathsarabandaraj, set null to the other values

```suggestion
    if (!email || !password) {
```

2023-07-23 03:24 UTC, anjula-sack requested changes

2023-07-23 03:24 UTC, anjula-sack commented on src/app.ts
> +app.use('/api/auth', userRouter);
```suggestion
app.use('/api/auth', authRoutes);
```

2023-07-23 03:24 UTC, anjula-sack commented on src/entity/user.entity.ts
> +import bcrypt from 'bcrypt';
let's rename this to `profile.entity.ts`

2023-07-23 03:28 UTC, anjula-sack requested changes

2023-07-23 03:28 UTC, anjula-sack commented on src/services/auth.service.ts
> +dotenv.config();
We don't have to import this since we are using it on app.ts
```suggestion
```

2023-07-23 03:28 UTC, anjula-sack commented on src/services/auth.service.ts
> +dotenv.config();
Is there an issue without it?

2023-07-23 03:28 UTC, anjula-sack commented on src/configs/passport.ts
> +dotenv.config();
```suggestion
```

2023-07-23 08:23 UTC, anjula-sack requested changes
Requested small changes

2023-07-23 08:23 UTC, anjula-sack commented on src/app.ts
> +export default server;
```suggestion
export default server;

```

Add the end of line

2023-07-23 08:23 UTC, anjula-sack commented on src/entity/profile.entity.ts
> +  type: string;
This should be an enum @sathsarabandaraj

2023-07-23 08:23 UTC, anjula-sack commented on src/entity/profile.entity.ts
> +export default Profile;
```suggestion
export default Profile;

```

2023-07-23 08:46 UTC, anjula-sack approved these changes
Great job! @sathsarabandaraj

2023-07-23 08:46 UTC, merged

2023-08-06 17:17 UTC, Piumal1999 commented
Hi @sathsarabandaraj, Could you please update the readme file with the instructions for setting the JWT secret key?