Bugfix/issue 138 request validation
sef-global/scholarx-backend pull request #146
Opened 2024-08-02 15:52 UTC by dsmabulage

## Purpose

The purpose of this PR is to fix #138 

## Goals
Add request validations via schema library to maintain consistent API parameters.

## Approach
Add Zod lib to schema validation
validation is done in the middleware level

### Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2024-08-04 05:45 UTC, anjula-sack requested changes

2024-08-04 05:45 UTC, anjula-sack commented on src/middlewares/requestValidator.ts
> +export const requestQueryValidator = (schema: ZodSchema<any, any, any>) => {
Can we define the types here?

2024-08-04 05:45 UTC, anjula-sack commented on src/middlewares/requestValidator.ts
> +  return (req: any, res: any, next: any) => {
Here as well. Let's avoid using any type

2024-08-05 04:06 UTC, dsmabulage commented on src/middlewares/requestValidator.ts
> +export const requestQueryValidator = (schema: ZodSchema<any, any, any>) => {
resolved

2024-08-05 04:06 UTC, dsmabulage commented on src/middlewares/requestValidator.ts
> +  return (req: any, res: any, next: any) => {
resolved

2024-08-07 14:07 UTC, dileepainivossl commented
@anjula-sack comments resolved

2024-08-07 14:21 UTC, merged