Get my profile endpoint implementation
sef-global/scholarx-backend pull request #23
Opened 2023-07-25 16:44 UTC by Shrenik0321

## Purpose
Implemented the get my profile endpoint.

## Goals
It sends an array of all table record objects when the api endpoint is called. 

## Approach
Built a simple api which uses the find() function to get all table records and send as a response.

### Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2023-07-26 02:26 UTC, anjula-sack requested changes

2023-07-26 02:26 UTC, anjula-sack commented on src/app.ts
> +app.use('/api/profile', profileRouter);
I made a change to the api: https://api-scholarx.sefglobal.org/api/me/profile

```suggestion
app.use('/api/me', profileRouter);
```

2023-07-26 02:26 UTC, anjula-sack commented on src/routes/profile.route.ts
> +profileRouter.get('/me', getProfile);
```suggestion
profileRouter.get('/profile', getProfile);
```

2023-07-26 02:26 UTC, anjula-sack commented on src/controllers/profile.controller.ts
> +    res.status(200).json({ allProfiles });
This should return only the logged-in user's profile. The request will contain the authorization header with the jwt token we are getting from the sign-in. That jwt token contains the userId. Using that you can fetch the profile.

2023-07-26 02:31 UTC, anjula-sack commented on src/routes/profile.route.ts
> +profileRouter.get('/me', getProfile);
Need to use the passport authentication

```suggestion
profileRouter.get('/profile',  passport.authenticate('jwt', { session: false }), getProfile);
```

2023-07-26 16:16 UTC, anjula-sack commented
@Shrenik0321 can you write tests for this?

2023-07-26 17:02 UTC, Shrenik0321 commented
> @Shrenik0321 can you write tests for this?

Sure. I've not written tests before but I can give it a try.

2023-07-26 17:08 UTC, anjula-sack commented
> 

No worries, It's time to learn. We can write tests for the controller and the service.

2023-07-26 17:15 UTC, Shrenik0321 commented
> > > @Shrenik0321 can you write tests for this?
> > 
> > 
> > Sure. I've not written tests before but I can give it a try.
> 
> No worries, It's time to learn. We can write tests for the controller and the service. @Shrenik0321

Alright, thanks. I'll be able to refer to that an write tests for future prs.

2023-07-27 06:53 UTC, anjula-sack commented
> > > > @Shrenik0321 can you write tests for this?
> > > 
> > > 
> > > Sure. I've not written tests before but I can give it a try.
> > 
> > 
> > No worries, It's time to learn. We can write tests for the controller and the service. @Shrenik0321
> 
> Alright, thanks. I'll be able to refer to that an write tests for future prs.

Great, can you write tests for this? Get some help with chatGPT. @Shrenik0321

2023-07-27 11:38 UTC, Shrenik0321 commented
> > > > > @Shrenik0321 can you write tests for this?
> > > > 
> > > > 
> > > > Sure. I've not written tests before but I can give it a try.
> > > 
> > > 
> > > No worries, It's time to learn. We can write tests for the controller and the service. @Shrenik0321
> > 
> > 
> > Alright, thanks. I'll be able to refer to that an write tests for future prs.
> 
> Great, can you write tests for this? Get some help with chatGPT. @Shrenik0321

yeah sure!

2023-08-01 15:49 UTC, anjula-sack requested changes

2023-08-01 18:57 UTC, Shrenik0321 commented on src/routes/profile.route.ts
> +  passport.authenticate('jwt', { session: false }),
Sure!

2023-08-02 02:41 UTC, anjula-sack requested changes

2023-08-02 02:41 UTC, anjula-sack commented on src/services/auth.service.ts
> +// import passport from 'passport';
Let's remove this line

```suggestion
```

2023-08-02 05:01 UTC, anjula-sack approved these changes
Good job! @Shrenik0321

2023-08-02 05:01 UTC, merged

2023-08-05 17:58 UTC, anjula-sack commented
Fixes #10