Implement the data models
sef-global/scholarx-backend pull request #46
Opened 2023-07-29 12:26 UTC by kumuditha-udayanga

## Purpose

The purpose of this PR is to fix #8 

## Goals

## Approach

### Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2023-08-05 10:17 UTC, anjula-sack requested changes

2023-08-05 10:17 UTC, anjula-sack commented on src/entity/email.entity.ts
> +    state: string
Let's create an enum type

2023-08-05 10:17 UTC, anjula-sack commented on src/entity/mentee.entity.ts
> +
mente, mentor relationship

```
 @ManyToOne(() => Mentor, mentor => mentor.mentees)
  mentor: Mentor;
```

2023-08-05 10:17 UTC, anjula-sack commented on src/entity/mentor.entity.ts
> +
```
@OneToMany(() => Mentee, mentee => mentee.mentor)
  mentees: Mentee[];
```

2023-08-05 10:17 UTC, anjula-sack commented on src/entity/mentor.entity.ts
> +    category: string
This will be a string

2023-08-05 10:17 UTC, anjula-sack commented
can you add the program entity as well @kumuditha-udayanga

2023-08-05 17:51 UTC, anjula-sack requested changes

2023-08-05 17:51 UTC, anjula-sack commented on src/entity/mentee.entity.ts
>      state: string
This is a enum. PENDING, REJECTED, ACCEPTED

2023-08-05 17:51 UTC, anjula-sack commented on src/entity/mentor.entity.ts
> +    category: string
Now this has a relationship. one to many with category

2023-08-05 17:51 UTC, anjula-sack commented on src/entity/platform.entity.ts
> +    category: string
```suggestion
```

2023-08-05 17:51 UTC, anjula-sack commented on src/enums/enums.ts
> +export enum EmailTypes {
```suggestion
export enum EmailStatusTypes {
```

2023-08-06 03:42 UTC, anjula-sack requested changes

2023-08-06 03:42 UTC, anjula-sack commented on src/entity/category.entity.ts
> +    }
```suggestion
    }
    
     @BeforeInsert()
  @BeforeUpdate()
  updateTimestamps() {
    this.updated_at = new Date();
    if (!this.uuid) {
      this.created_at = new Date();
    }
  }

  @BeforeInsert()
  async generateUuid() {
    if (!this.uuid) {
      this.uuid = uuidv4();
    }
  }
```

2023-08-06 03:42 UTC, anjula-sack commented on src/entity/category.entity.ts
> +    id!: bigint
```suggestion
    uuid!: bigint
    
     @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
     created_at: Date | undefined;

     @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
     updated_at: Date | undefined;
```

2023-08-06 03:42 UTC, anjula-sack commented on src/entity/email.entity.ts
> +    id!: bigint
```suggestion
    uuid!: bigint
```

2023-08-06 03:42 UTC, anjula-sack commented on src/entity/email.entity.ts
> +    created_at: Date | undefined
```suggestion
    @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
     created_at: Date | undefined;
     
     @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
     updated_at: Date | undefined;
```

2023-08-06 03:42 UTC, anjula-sack commented on src/entity/email.entity.ts
> +    }
```suggestion
    }
    
   @BeforeInsert()
  @BeforeUpdate()
  updateTimestamps() {
    this.updated_at = new Date();
    if (!this.uuid) {
      this.created_at = new Date();
    }
  }
  
  @BeforeInsert()
  async generateUuid() {
    if (!this.uuid) {
      this.uuid = uuidv4();
    }
  }
```

2023-08-06 03:42 UTC, anjula-sack commented on src/entity/mentee.entity.ts
> +    id!: bigint
```suggestion
    uuid!: bigint
```

2023-08-06 03:42 UTC, anjula-sack commented on src/entity/mentor.entity.ts
> +    id!: bigint
```suggestion
    uuid!: bigint
```

2023-08-06 03:42 UTC, anjula-sack commented on src/entity/mentor.entity.ts
> +    updated_at: Date | undefined
Update this just like above,

refer to the existing profile entity

2023-08-06 03:42 UTC, anjula-sack commented on src/entity/platform.entity.ts
> +    id!: bigint
```suggestion
    uuid!: bigint
```

2023-08-06 03:42 UTC, anjula-sack commented on src/types.ts
> +}
```suggestion
}

```

2023-08-06 13:25 UTC, anjula-sack commented
@kumuditha-udayanga can you fix the conflicts?

2023-08-06 16:18 UTC, kumuditha-udayanga commented
Sure @anjula-sack, I'll resolve them as well.

2023-08-11 04:52 UTC, anjula-sack commented
Hi @kumuditha-udayanga, any updates on this?

2023-08-11 15:14 UTC, anjula-sack approved these changes
Thank you! @kumuditha-udayanga

2023-08-11 15:14 UTC, merged