Delete my profile implemented
sef-global/scholarx-backend pull request #54
Opened 2023-08-12 10:28 UTC by Danishkar

## Purpose

The purpose of this PR is to fix #11<issue-number>

## Goals

## Approach

### Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2023-08-12 11:31 UTC, anjula-sack requested changes
can you write tests as well? @Danishkar

2023-08-12 11:31 UTC, anjula-sack commented on src/controllers/profile.controller.ts
> +      await deleteProfile(user)
```suggestion
      await deleteProfile(user.uuid)
```

2023-08-12 11:31 UTC, anjula-sack commented on src/services/profile.service.ts
> +export const deleteProfile = async (user: Profile): Promise<void> => {
```suggestion
export const deleteProfile = async (userId: string): Promise<void> => {
```

2023-08-12 11:32 UTC, anjula-sack requested changes

2023-08-12 11:32 UTC, anjula-sack commented on src/controllers/profile.controller.ts
> +    const user = await getProfile(req)
```suggestion
    const user = req.user
```

2023-08-13 17:34 UTC, anjula-sack commented
Hi @Danishkar, can you fix the conflicts?

2023-08-15 15:50 UTC, Danishkar commented
> Hi @Danishkar, can you fix the conflicts?

yea sure

2023-08-16 10:17 UTC, Danishkar commented
> can you write tests as well? @Danishkar

i will work on that

2023-08-16 13:11 UTC, anjula-sack commented
> > Hi @Danishkar, can you fix the conflicts?
> 
> yea sure

Can you fix the lint errors as well? Run `npm run lint:fix`

2023-08-16 13:19 UTC, Danishkar commented
> npm run lint:fix

done

2023-08-17 13:32 UTC, anjula-sack requested changes
@Danishkar can you run lint fix again? The CI is failing.

2023-08-19 06:15 UTC, anjula-sack commented
@Danishkar the tests are failing

2023-08-19 15:50 UTC, Danishkar commented
> @Danishkar the tests are failing

yea bro I am new to this jest testing I will check on that.

2023-08-19 15:52 UTC, anjula-sack requested changes
Requested some changes

2023-08-19 15:52 UTC, anjula-sack commented on src/controllers/profile.controller.ts
> +    const userId = req.params.uuid
```suggestion
```

2023-08-19 15:52 UTC, anjula-sack commented on src/controllers/profile.controller.ts
> +    if (!user || user.uuid !== userId) {
```suggestion
    if (!user) {
```

2023-08-19 15:52 UTC, anjula-sack commented on src/routes/profile/profile.route.ts
> +profileRouter.delete('/profile/:uuid', requireAuth, deleteProfileHandler)
```suggestion
profileRouter.delete('/profile', requireAuth, deleteProfileHandler)
```

2023-08-22 10:42 UTC, anjula-sack commented on src/routes/profile/profile.route.test.ts
> +  })
```suggestion
  })
  
```

2023-08-22 10:42 UTC, anjula-sack commented on src/routes/profile/profile.route.test.ts
>      })
```suggestion
    })
    
```

2023-08-22 10:52 UTC, anjula-sack commented on src/routes/profile/profile.route.test.ts
> +
```suggestion
 
```

2023-08-22 10:52 UTC, anjula-sack commented on src/routes/profile/profile.route.test.ts
> +
```suggestion
 
```

2023-08-22 10:55 UTC, anjula-sack commented
@Danishkar can you take a pull and fix the lint issues @Danishkar

2023-08-22 11:57 UTC, anjula-sack approved these changes
Good job! @Danishkar

2023-08-22 11:57 UTC, merged