Implement mentor availability endpoint
sef-global/scholarx-backend pull request #64
Opened 2023-09-18 08:00 UTC by Shrenik0321

## Purpose
The purpose of this endpoint is for the mentor to update their availability

## Goals

## Approach

### Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2023-09-18 08:02 UTC, Shrenik0321 commented
I havent written the tests yet. Wanted to make sure the endpoint is fine. Will do once approved. Also im not sure about the route @anjula-sack

2023-09-18 15:49 UTC, anjula-sack requested changes

2023-09-18 15:49 UTC, anjula-sack commented on src/routes/profile/profile.route.ts
> +)
This should go to mentor routes @Shrenik0321

2023-09-23 06:12 UTC, anjula-sack requested changes

2023-09-23 06:12 UTC, anjula-sack commented on src/routes/admin/admin.route.test.ts
> +    }
You can import this from mock.ts.

2023-09-23 06:12 UTC, anjula-sack commented on src/routes/admin/admin.route.test.ts
> +const randomStringAdmin = Math.random().toString(36)
This can be removed. Check mock.ts

2023-09-23 16:00 UTC, anjula-sack approved these changes
Thank you! @Shrenik0321

2023-09-23 16:01 UTC, merged