Update get mentor categories endpoint (public) to send category IDs
sef-global/scholarx-backend pull request #83
Opened 2023-12-23 13:01 UTC by Madhawa97

## Purpose

The purpose of this PR is to fix #82 

## Goals
Currently, the api/categories endpoint only returns a list of category names. The category IDs are also required during the mentor application process.

## Approach
Add the category IDs to the response.
Sample response: 
```json
{
    "categories": [
        {
            "category": "Data Science",
            "id": "95ba00c0-8173-43c4-9573-6b481b4085e2"
        },
        {
            "category": "Random Category",
            "id": "fe7ca629-4f5e-440a-86cb-d54f8b98ec5f"
        },
        {
            "category": "Computer Science",
            "id": "fef68adb-e710-4d9e-8772-dc4905885088"
        }
    ],
    "message": "All Categories found"
}
```

### Screenshots
N/A
##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2023-12-23 16:10 UTC, Madhawa97 commented
Tests are passing locally.
<img width="1172" alt="image" src="https://github.com/sef-global/scholarx-backend/assets/70215958/17c942a9-8c0b-45b3-9a31-48003d60165c">

2023-12-24 10:52 UTC, anjula-sack commented on src/services/category.service.ts
> +}
```suggestion
interface Category {
  category: string
  id: string
}
```

2023-12-24 10:52 UTC, anjula-sack requested changes

2023-12-24 10:52 UTC, anjula-sack commented on src/services/category.service.ts
> +  categories?: CategoryType[] | null
```suggestion
  categories?: Category[] | null
```

2024-01-03 15:28 UTC, anjula-sack commented
@Madhawa97 Can you add the requested changes?

2024-01-03 16:04 UTC, Madhawa97 commented
Hi @anjula-sack, Can you check now, please?

2024-01-03 17:18 UTC, anjula-sack approved these changes
Thank you @Madhawa97

2024-01-03 17:18 UTC, merged